workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.godroll.app
      vars:
        XCODE_WORKSPACE: "apps/web/ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build:web

      - name: Sync Capacitor
        script: |
          cd apps/web
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_IDENTIFIER" --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd apps/web/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          cd apps/web/ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/output \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - apps/web/ios/App/build/output/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  ios-simulator:
    name: iOS Simulator Build (Testing)
    max_build_duration: 30
    instance_type: mac_mini_m2

    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true

    environment:
      vars:
        XCODE_WORKSPACE: "apps/web/ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build:web

      - name: Sync Capacitor
        script: |
          cd apps/web
          npx cap sync ios

      - name: Build for Simulator
        script: |
          cd apps/web/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

    artifacts:
      - apps/web/ios/App/build/**/*.app
